### ISSUE TITLE
Not working on FF

### ISSUE THREAD

**Issue by kidCubi** [antistatique/esti-mate#5]
### 💬 Describe the bug
Tested on Firefox 88.0.1 desktop | MacOS
The plugin doesn't fire up after installation. I cannot re-install it since the page of the plugin has been taken down 🤭 

Ping @gido @Yago

**Comment by gido** [comment]
We need to rework our copy:

> **Rejected**
> 
> This add-on didn't pass review because of the following problems:
> 
> 1) This add-on is creating DOM nodes from HTML strings containing potentially unsanitized data, by assigning to innerHTML, jQuery.html, or through similar means. Aside from being inefficient, this is a major security risk. For more information, see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page . Here are some examples that were discovered:
> 
> - src\lib\airtable.js line 113, 149
> 
> - src\lib\summary.js line 101
> 
> In addition, the following is required to complete the review:
> 
> 1) Established libraries must be included from their official source, in their original format without any modification (changing the file name does not matter). Please note that only stable releases are acceptable (not beta, pre, RC, dev etc) and that third party CDNs are not considered official sources. For more information, please read https://extensionworkshop.com/documentation/publish/third-party-library-usage/ . For the next release, please make sure you comply with our third party library rules.
> 
> - lib/rxjs-6.6.7.umd.min.js

**Comment by gido** [comment]
Submitted version 1.6.0, let's see if the review pass !

@kidCubi I'm waiting on the new icon ;-)

**Comment by gido** [comment]
Chrome Extension:

```
- A justification for webRequest is required. This can be entered on the Privacy practices tab.
- Icon image is missing.
- The single purpose description is required. This can be entered on the Privacy practices tab.
- To publish your item, you must certify that your data usage complies with our Developer Program Policies. You can certify this on the Privacy practices tab of the item edit page.
- You must provide a contact email before you can publish any item. Enter your contact email on the Account tab.
```

**Comment by gido** [comment]
validé!
https://addons.mozilla.org/en-US/firefox/addon/esti-mate/
